import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import { ApiKeyProvider } from "@hooks/useApiKey";
import CssBaseline from "@mui/material/CssBaseline";
import type { Metadata } from "next";

import ClientThemeProvider from "./clientThemeProvider";
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "μs.ly — the Cereal Data Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientThemeProvider>
          <ApiKeyProvider>
            <CssBaseline />
            {children}
          </ApiKeyProvider>
        </ClientThemeProvider>
      </body>
    </html>
  );
}
